//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoditasAssignment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemModifire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemModifire()
        {
            this.OrderItemModifires = new HashSet<OrderItemModifire>();
        }
    
        public int id { get; set; }
        public int item_id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemModifire> OrderItemModifires { get; set; }
    }
}
