//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoditasAssignment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modifire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Modifire()
        {
            this.OrderProductModifires = new HashSet<OrderProductModifire>();
            this.ProductModifires = new HashSet<ProductModifire>();
        }
    
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductModifire> OrderProductModifires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductModifire> ProductModifires { get; set; }
    }
}
